### ISSUE TITLE
Inclues collection

### ISSUE THREAD

**Issue by aguilera51284** [Brian-McBride/feathers-arangodb#7]
hi, Is there any way to do includes, so there is no need to perform 2 queries on the db?
you have a example?

**Comment by Brian-McBride** [comment]
Can you give me an example of what you are trying to use includes with?

The database connector supports the basic CRUD and Query that FeathersJS expects out of the box:
https://docs.feathersjs.com/api/databases/querying

Unfortunately, basic CRUD only goes so far. And an ORM layer like FeathersJS query is simple so that it can be easily applied to multiple database types. But don't forget that you can run your own AQL query either in a hook or override the actual service method itself. 

Say you had a service called "friends" . You can override methods.

```javascript
const createService = require('../../connectors/feathers-arangodb');
const myService = createService();

// Now you could override a method
myService.get = async (id, params) => {
  // Create a query
  let queryString = aql`
  FOR u IN users
    FILTER u.active == true
    LIMIT 0, 4
    RETURN {
      "user" : u.name,
      "friendIds" : (
        FOR f IN relations
          FILTER f.friendOf == u.userId && f.type == "friend"
          FOR u2 IN users
            FILTER f.thisUser == u2.useId
            RETURN u2.name
      )
    }
  `;

  // Get the cursor
  let cursor = await myService.query(queryString);

  // Do something with it - in this case, get all the data in an array and return that
 return cursor.all();
}

app.use('/friends', myService);
```

To be fair, I just typed this up and used an example of a JOIN query from the ArangoDB Docs. What I'm saying is... I think this will work, but I didn't actually test it. The point is that you can run your own complex queries with AQL. 

Remember, all database connectors are just services that observe some (hopefully all) of the expected methods: create, get, find, update, patch, remove and the common API and Querying.

References:
https://docs.feathersjs.com/api/services.html
https://docs.feathersjs.com/api/databases/common.html
https://docs.feathersjs.com/api/databases/querying.html

**Comment by Brian-McBride** [comment]
Hi @aguilera51284 
I have completely re-written this service. 

Largely it remains the same. In the readme is an example where I make a second AQL query inside a hook. 

The way I structured this app, you can do a lot more. You can extend methods from the service itself. You can do work in hooks. And you can also extend the full class, just changing the methods you need. Here is an example of subclassing:

```javascript

const feathers = require('@feathersjs/feathers');
const DbService = require('feathers-arangodb').DbService;
const aql = require('arangojs').aql;

class MySpecialService extends DbService {
  constructor(props) {
    super(props);
  }

  async get(id, params) {
    // Always use connect to get your references, this makes sure that they are ready
    const { database, collection } = this.connect();

    // A multi query
    const cursor = await database(aql`
    FOR p IN persons
      LET recommendations = (
        FOR r IN recommendations
          FILTER p.id == r.personId
          SORT p.rank DESC
          LIMIT 10
          RETURN r
      )
      RETURN { person : p, recommendations : recommendations }
    `)
    
    // Do something with the result, in this case, just pass out the promise
    return cursor.all();
  }

}
const options = {
  collection: 'TODOS',
  database: 'YOUR_DATABASE_NAME',
  authType: AUTH_TYPES.BASIC_AUTH,
  username: 'root',
  password: 'root',
};
const service = new MySpecialService(options);

const app = feathers('persons', service);

```

Please comment on the issue if you have any more questions.
